### ISSUE TITLE
Function 'BetterPrinting.creatF()' does not close file

### ISSUE THREAD

**Issue by NickolaiBeloguzov** [Butter-mit-Brot/BetterPrinting#1]
This function does not close current file via 'file.close()' method, which can result in difficulties during further file manipulations.

Examples of such problems:
- You may not be able to read file/write to file again until your program exits
- You may not be able to move/delete this file until your program exits

The reason is that when you open a file in Python interpreter locks this file (no major operations can be performed with it) until you explicitly tell Python to release it (which you can do via close() method) OR until your entire script finishes executing.
Plus, until you call close() method, Python will not release file's contents from memory, which can result in major memory consumption increase if you have a large file.

_Sidenote: why is your function named creatF? is it a typo? If not, then sorry for asking_

**Comment by Butter-mit-Brot** [comment]
I completely forgot about that thanks!

and yes it was a typo I already fixed it in the next version that comes with all you improvements thanks
