### ISSUE TITLE
Replace functions BetterPrinting.oneLine() .. BetterPrinting.fiveLine() with a more convenient function BetterPrinting.printLines() 

### ISSUE THREAD

**Issue by NickolaiBeloguzov** [Butter-mit-Brot/BetterPrinting#2]
This library is very good, but there is one main bottleneck

So your package right now has five separate functions for handling five different cases, which is not very flexible.

Ok, so right now using your library I can print up to five lines per function call. But what if I have ten lines which need to be printed? Do I call BetterPrinting.fiveLine() function twice? This is not very efficient.

This situation of having one function for every number of lines also can and WILL cause an overhead for the developer, i.e. for you.
Suppose there is a vulnerability discovered in standard print() function. You, as a good and responsible developer, want to make users of your library safe and design a custom print_s() function, where this vulnerability is gone. But now you need to go to 
every function which uses print() function and replace it. Again, not very efficient.

**Solution:**
Replace your functions from BetterPrinting.oneLine() to BetterPrinting.fileLine() with one function called BetterPrinting.printLines(). Here's a code snippet with full function declaration and some comments explaining the benefits:
```python
def printLines(*args):
#This *args parameter means that this function can accept ANY number of arguments and stores them in a list called 'args'
    print("\n".join(args)) #Joining all passed lines with a \n and printing it
```

This is way more convenient for the developer to maintain and allows more flexibility for the end user.
Here are some examples that demonstrate new possibilities:
```python
import BetterPrinting as bt

bt.printLines("Hello world!", "Goodbye world!")
# Output:
# 
# Hello world!
# Goodbye world!

bt.printLines("Wow", "this", "is", "way", "more", "flexible", "than", "before")
# Output:
# 
# Wow
# this
# is
# way
# more
# flexible
# than
# before
```

Not only that, but now all your functionality is concentrated inside just one function, thus allowing you to implement any additional logic (e.g. removing special characters, capitalizing lines, etc...) without replicating this functionality more than once

**Comment by Butter-mit-Brot** [comment]
Oh I know about that but my dumbass brain did not think about this :)
Thank you I will write this on my To Do list :)
